  
print(10+(2+6)-91) 
print(10-(10+9))
print(10*(9-6+4))
print(10//(2+3))
print(10 % 6)
print(10)
print(1 == 2)
print(1==1)
print(1 != 2)
print(1 != 1)
print(1 > 1)
print(1 >= 1)
print(1 <= 1)
print(1 < 1)
print(1>2 and False)
print(True and False)
print(True and True)

print(2>1 or True)
print(False or True)
print(False or False)
print(True == False)
print(True != False)
print(True <  False)
print(True <= False)
print(True >  False)
print(True >= False)
